version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLAG=TSGLIVE{go_routine_is_fun_yeyeyyeyeyeyey}
    ports:
      - '8080:8080'
